name: Build and Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install
        
      - name: Generate
        run: yarn generate
      - name: Build Backend
        run: yarn workspace backend build
      - name: Test Backend
        run: yarn workspace backend tsc --noEmit
      
      - name: Test Frontend
        run: yarn workspace frontend tsc --noEmit
  vitest:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:${{ runner.temp }}/test.db
      SESSION_SECRET: "rftgvyhbjunkmlftghbjnkmghbjnklfcgvhbnj"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install
      - name: Generate
        run: yarn workspace backend generate
      - name: Build Backend
        run: yarn workspace backend build
      - name: Prisma Deploy
        run: yarn workspace backend prisma migrate deploy
      - name: Seed Database
        run: yarn workspace backend prisma db seed
      - name: Run Tests
        run: yarn workspace backend test